### ISSUE TITLE
Missing action behind the 'vault drops value' edit button

### ISSUE THREAD

**Issue by gumbleliks** [defichain-api/dobby-frontend#6]
A bit confusing regarding the UX is that there is no function/action mapped to the edit button of the "vault drops" value. It is possible by clicking on the value directly, but without an helpful mouseover icon action.

![image](https://user-images.githubusercontent.com/4319708/161750539-1f872d7a-bd33-4b0d-b585-4229bb68d786.png)

**Comment by DerFuchs** [comment]
Fixed, will be included in next UI release.

Thank you so much for reporting <3
